smart_university_fullStack/api/urls.py
from django.urls import path
from .views import ControlSettingsView

urlpatterns = [
    # Your other URL patterns here
    path('control-settings/', ControlSettingsView.as_view(), name='control_settings_api'),
]

smart_university_fullStack/smart_university/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user_interface.urls')),
    path('',include('users.urls')),
    path('',include('data_collect.urls')),
    path('api/',include('api.urls'))
]

smart_university_fullStack/user_interface/urls.py
from django.urls import path,include
from . import views
       
urlpatterns=[
    path('',views.home,name='home'),
    # path('login',include('django.contrib.auth.urls')  )
    path('logout/',views.userLogout,name='logout' ),
    path('register/',views.create_student,name='register'),
    path('login/',views.login_user,name='login'),
    path('student_dashboard/',views.student_dashboard,name='student_dashboard'),
    path('teacher_dashboard/',views.teacher_dashboard,name='teacher_dashboard'),
    path('admin_dashboard/',views.admin_dashboard,name='admin_dashboard'),
    path('technical_team_dashboard/',views.technical_team_dashboard,name='technical_team_dashboard'),
    path('control_settings/', views.control_settings, name='control_settings'),
    path('control_settings_react/', views.control_settings_react, name='control_settings_react'),
    path('admin_attandance_dashboard/', views.admin_attandance_dashboard, name='admin_attandance_dashboard'),

]


smart_university_fullStack/user_interface/forms.py
from django import forms
from django.contrib.admin.widgets import AdminSplitDateTime,AdminTimeWidget

from django.forms.widgets import TimeInput,DateTimeInput

from .models import Student,SetSession
from data_collect.models import *


class CustomDateTimeWidget(DateTimeInput):
    input_type = 'datetime-local'

class SetSessionForm(forms.ModelForm):
    class Meta:
        model = SetSession
        fields = '__all__'

    # Use the custom date and time widget for the time field
    time = forms.DateTimeField(widget=CustomDateTimeWidget(attrs={'format': f'%Y-%m-%dT%H:%M'}))

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['id_number', 'contact_phone', 'group_number']
    password = forms.CharField(widget=forms.PasswordInput)

class ControlSettingsFormPublish(forms.ModelForm):
    class Meta:
        model = ControlSettingsPublish
        fields = ['water_pump_status', 'block1_status', 'block2_status', 'block3_status']
class ControlSettingsForm(forms.ModelForm):
    class Meta:
        model = ControlSettingsRecive
        fields = ['water_pump_status', 'block1_status', 'block2_status', 'block3_status','fire_detection','gas_detection']

smart_university_fullStack/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import CustomUser  # Import your CustomUser model
class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(help_text='A valid email address, please.', required=True)
    role = forms.ChoiceField(choices=CustomUser.Role.choices)  # Add role field to the form

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

    def save(self, commit=True, is_active=True, is_superuser=False, is_staff=False):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.role = self.cleaned_data['role']  # Assign the role from form data
        user.is_active = is_active
        user.is_superuser = is_superuser
        user.is_staff = is_staff
        if commit:
            user.save()
        return user
    

# class SuperUserRegistrationForm(UserCreationForm):
#     email = forms.EmailField(help_text='A valid email address, please.', required=True)
#     role = forms.ChoiceField(choices=CustomUser.Role.choices)  # Add role field to the form

#     class Meta:
#         model = get_user_model()
#         fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

#     def save(self, commit=True):
#         user = super(UserRegistrationForm, self).save(commit=False)
#         # user.
#         user.email = self.cleaned_data['email']
#         user.role = self.cleaned_data['role']  # Assign the role from form data
#         if commit:
#             user.save()
#         return user

smart_university_fullStack/user_interface/views.py
from django.shortcuts import render, redirect
import time 
# from .anti_spoofing.test  import test 
from django.http import JsonResponse
from .forms import *
from .models import *
from data_collect.models import *
from django.contrib.auth import authenticate, login ,logout       
from django.shortcuts import render, redirect          
from django.contrib.auth.decorators import  login_required
from .decorators import notLoggedUsers , forAdmins
from users.forms import UserRegistrationForm
def home(request):   
    return render(request,'AI/visitors_page/index.html')

#    ------------------------------------------ student dash board -----------------
@login_required(login_url='login_student')
def student_dashboard(request):
    if request.user.role != 'STUDENT':
        return redirect('login_student')
    # Get the student object for the logged-in user
    student = Student.objects.get(user=request.user)
    # Get the attendance objects for the student
    attendance_objects = Attendance.objects.filter(student=student)
    # Create a list to store attendance information for rendering in the template
    attendance_info = []
    # Loop through the attendance objects
    user_info = {
        'first_name': request.user.first_name,
        'last_name': request.user.last_name,
    }
    for attendance in attendance_objects:
        session_info = {
            'time': attendance.session.time,
            'class_name': attendance.session.class_name,
            'group': attendance.session.group.group_name,
            'teacher': f'{attendance.session.teacher.user.first_name} {attendance.session.teacher.user.last_name}',
            'module': attendance.session.teacher.module,
        }
        attendance_info.append(session_info)

    return render(request, 'AI/students/dashboard_students.html', {'attendance_info': attendance_info,'user_info':user_info})

#    ------------------------------------------- teacher dashboard -----------------

@login_required(login_url='login_student')
def teacher_dashboard(request):
    if request.user.role != 'TEACHER':
        return redirect('login')

    # Get the teacher object for the logged-in user
    teacher = Teacher.objects.get(user=request.user)
     # Find all sessions that contain this teacher
    groups = GR_number.objects.all()
    sessions_taught = SetSession.objects.filter(teacher=teacher)
    # Get the teacher's sessions
    teacher_attandance = Attendance.objects.filter(teacher=teacher)

    # Create a list to store session information for rendering in the template
    session_teacher_info = []
    session_students_info = []
    user_info={
        'first_name': request.user.first_name,
        'last_name': request.user.last_name,
    }
    # Loop through the teacher's sessions
    for attendance in teacher_attandance:
        session_data = {
            'group': attendance.session.group.group_name,
            'student_name':attendance.session.group.group_name,
            'class_name': attendance.session.class_name,
            'module': teacher.module,
            'time': attendance.session.time,
        }
        session_teacher_info.append(session_data)
    # Loop through the sessions taught by the teacher
    for session in sessions_taught:
        # Find all attendance records for the current session
        attendances = Attendance.objects.filter(session=session)

        # Loop through the attendance records
 
        for attendance in attendances:
                            # Check if the attendance record has a student
            if ( attendance.student is not None ) :
            
                    session_data = {
                                    'group': attendance.student.group_number.group_name,
                                    'student_name': f'{attendance.student.user.first_name} {attendance.student.user.last_name}',
                                    'module': session.teacher.module,
                                    'class_name': session.class_name,
                                    'time': session.time,
                                        }
                    session_students_info.append(session_data)
    return render(request, 'AI/teachers/dashboard_teachers.html', {'session_teacher_info': session_teacher_info,'session_students_info': session_students_info,'user_info': user_info})

@login_required(login_url='login')
@forAdmins
def admin_attandance_dashboard(request):
    admin_info = {
        'first_name': request.user.first_name,
        'last_name': request.user.last_name,
    }

    # Get the teacher's sessions
    attendances = Attendance.objects.all()
  
    # Create a list to store session information for rendering in the template
    session_teachers_info = []
    session_students_info = []
   
    # Loop through the teacher's sessions
    for attendance in attendances:
        if attendance.teacher is not None :
            print('------------------------------------------------------------------',attendance.session.time)
            session_data = {
                'group': attendance.session.group.group_name,
                'teacher_name':f'{attendance.teacher.user.first_name} {attendance.teacher.user.last_name}',
                'class_name': attendance.session.class_name,
                'module': attendance.teacher.module,
                'time': attendance.session.time,
            }
            session_teachers_info.append(session_data)
    # Loop through the sessions taught by the teacher
    for attendance in attendances:
            if attendance.student is not None :
                session_data = {
                    'group': attendance.student.group_number,
                    'student_name': f'{attendance.student.user.first_name} {attendance.student.user.last_name}',
                    'class_teacher':f'{attendance.session.teacher.user.first_name} {attendance.session.teacher.user.last_name}',
                    'module': attendance.session.teacher.module,
                    'class_name': attendance.session.class_name,
                    'time': attendance.session.time,
                }
                session_students_info.append(session_data)
    return render(request, 'AI/administration/attandance_list.html', {'session_teachers_info': session_teachers_info,'session_students_info': session_students_info,'user_info': admin_info})


@login_required(login_url='login')
@forAdmins
def admin_dashboard(request):
    admin_info = {
        'first_name': request.user.first_name,
        'last_name': request.user.last_name,
    }

    if request.method == 'POST':
        form = SetSessionForm(request.POST)
        form1 = UserRegistrationForm(request.POST)
        
        if form.is_valid():
            form.save()
            print("session created")
        else:
            print("SetSessionForm errors:", form.errors)

        if form1.is_valid():
            # Extract data from form submission
            id_number = request.POST.get('id_number')
            contact_phone = request.POST.get('contact_phone')
            group_name = request.POST.get('group_name')
            Module = request.POST.get('Module')
            position = request.POST.get('position')
            is_supervisor=request.POST.get('is_supervisor')
            if form1.cleaned_data['role'] == "STUDENT":
                user = form1.save()  
                print('User created')
                group_number = GR_number.objects.get(group_name=group_name)
                Student.objects.create(
                    #  created_by=request.user,
                    user=user,
                    id_number=id_number,
                    contact_phone=contact_phone,
                    group_number=group_number
                )
            if request.user.is_superuser and form1.cleaned_data['role'] == "ADMIN":
                    if is_supervisor == 'YES':
                        user = form1.save(is_staff=True,is_superuser=True) 
                    elif  is_supervisor == 'NO':  
                        user = form1.save() 
                    Administration.objects.create(
                            # created_by=request.user,
                            user=user,
                            id_number=id_number,
                            contact_phone=contact_phone,
                        )
            if form1.cleaned_data['role'] == "TEACHER":
                user = form1.save()  
                print('User created')
                Teacher.objects.create(
                    #  created_by=request.user,
                    user=user,
                    id_number=id_number,
                    contact_phone=contact_phone,
                    module=Module.lower(),
                )
            if form1.cleaned_data['role'] == "TECHNICAL_TEAM":
                user = form1.save()  
                print('User created')
                TechnicalTeam.objects.create(
                    #  created_by=request.user,
                    user=user,
                    id_number=id_number,
                    position=position.lower(),
                    contact_phone=contact_phone,
                )     
        else:
            print("UserRegistrationForm errors:", form1.errors)
    else:
        form = SetSessionForm()
        form1 = UserRegistrationForm()
    return render(request, 'AI/administration/dashboard_administration.html', {'form': form, 'form1': form1, 'admin_info': admin_info})

#    -------------------------------------------- techneical team dash board -------
@login_required(login_url='login_student')
def technical_team_dashboard(request):
    if request.user.role != 'TECHNICAL_TEAM':
        return redirect('login_student')

smart_university_fullStack/user_interface/templates/AI/administration/attandance_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin Pannel</title>
    <link rel="stylesheet" href={% static "/css/all.min.css" %}> <link
    rel="stylesheet" href={% static "/css/teacher_dashboard_style.css" %}>
  </head>
  <body>
    <div class="container">
      <div class="topbar">
        <div class="logo">
          <h2>IGEE</h2>
        </div>

        <i class="fas fa-bell"></i>
        <div class="user"><img src={% static "/images/user.png" %} alt=""></div>
      </div>
      <div class="sidebar">
        <ul>
            <li>
            <a href="{% url 'admin_dashboard' %}">
                <i class="fas fa-cog"></i>
                <div>Dashboard</div>
            </a>
         </li>
        </li>
            <li>
                <a href="{% url 'admin_attandance_dashboard' %}">
                    <i class="fas fa-user-graduate"></i>
                    <div>Students and Teachers</div>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fas fa-cog"></i>
                    <div>Settings</div>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fas fa-question"></i>
                    <div>Help</div>
                </a>
            </li>
        </ul>
    </div>
      <div class="main">
        <div class="cards">
          <div class="card">
            <div class="card-content">
              <div class="number">1217</div>
              <div class="card-name">Students</div>
            </div>
            <div class="icon-box">
              <i class="fas fa-user-graduate"></i>
            </div>
          </div>
          <div class="card">
            <div class="card-content">
              <div class="number">42</div>
              <div class="card-name">Teachers</div>
            </div>
            <div class="icon-box">
              <i class="fas fa-chalkboard-teacher"></i>
            </div>
          </div>
          <div class="card">
            <div class="card-content">
              <div class="number">68</div>
              <div class="card-name">Employees</div>
            </div>
            <div class="icon-box">
              <i class="fas fa-users"></i>
            </div>
          </div>
          <div class="card">
            <div class="card-content">
              <div class="number">$4500</div>
              <div class="card-name">Earnings</div>
            </div>
            <div class="icon-box">
              <i class="fas fa-dollar-sign"></i>
            </div>
          </div>
        </div>
        <div class="charts">
          <div class="chart">
            <h2>Welcome {{user_info.first_name}} {{user_info.last_name}}</h2>
          </div>

          <div class="chart" id="daughnut-chart">
            <h2>Absence Information</h2>
            <!-- Add this inside your HTML body where you want to display the teacher's session information -->
            <div class="session-table">
              <h2>Teachers Absences</h2>
              <table>
                <thead>
                  <tr>
                    <th>Teacher Name</th>
                    <th>Assigned Group</th>
                    <th>Class Name</th>
                    <th>Module</th>
                    <th>Time</th>
                  </tr>
                </thead>
                <tbody>
                  {% for session_data in session_teachers_info %}
                  <tr>
                    <td>{{ session_data.teacher_name }}</td>
                    <td>{{ session_data.group }}</td>
                    <td>{{ session_data.class_name }}</td>
                    <td>{{ session_data.module }}</td>
                    <td>{{ session_data.time }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
          <div class="chart" id="daughnut-chart1">
            <h2>Absence Information</h2>
            <!-- Add this inside your HTML body where you want to display the teacher's session information -->
            <div class="session-table">
              <h2>Students Absences</h2>
              <table>
                <thead>
                  <tr>
                    <th>Group</th>
                    <th>Student Name</th>
                    <th>Class Name</th>
                    <th>Module</th>
                    <th>Time</th>
                  </tr>
                </thead>
                <tbody>
                  {% for session_data in session_students_info %}
                  <tr>
                    <td>{{ session_data.group }}</td>
                    <td>{{ session_data.student_name }}</td>
                    <td>{{ session_data.class_name }}</td>
                    <td>{{ session_data.module }}</td>
                    <td>{{ session_data.time }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

smart_university_fullStack/user_interface/templates/AI/administration/dashboard_administration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Pannel</title>
    <link rel="stylesheet" href={% static "/css/all.min.css" %}>
    <link rel="stylesheet" href={% static "/css/admin_dashboard_style.css" %}>
</head>
<body>
    <div class="container">
        <div class="topbar">
            <div class="logo">
                <h2>IGEE</h2>
            </div>
            <i class="fas fa-bell"></i>
            <div class="user">
                <img src={% static "/images/user.png" %} alt="">
            </div>
        </div>
        <div class="sidebar">
            <ul>
                <li>
                <a href="{% url 'admin_dashboard' %}">
                    <i class="fas fa-cog"></i>
                    <div>Dashboard</div>
                </a>
             </li>
            </li>
                <li>
                    <a href="/admin_attandance_dashboard">
                        <i class="fas fa-user-graduate"></i>
                        <div>Students and Teachers</div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-cog"></i>
                        <div>Settings</div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-question"></i>
                        <div>Help</div>
                    </a>
                </li>
            </ul>
        </div>
        <div class="main">
            <div class="cards">
                <div class="card">
                    <div class="card-content">
                        <div class="number">1217</div>
                        <div class="card-name">Students</div>
                    </div>
                    <div class="icon-box">
                        <i class="fas fa-user-graduate"></i>
                    </div>
                </div>
                <div class="card">
                    <div class="card-content">
                        <div class="number">42</div>
                        <div class="card-name">Teachers</div>
                    </div>
                    <div class="icon-box">
                        <i class="fas fa-chalkboard-teacher"></i>
                    </div>
                </div>
                <div class="card">
                    <div class="card-content">
                        <div class="number">68</div>
                        <div class="card-name">Employees</div>
                    </div>
                    <div class="icon-box">
                        <i class="fas fa-users"></i>
                    </div>
                </div>

            </div>
            <div class="charts">
                <div class="chart ">
                    <h2>Create Users</h2>
                    {% comment %} <div class="admin-info ">
                        <h2>{{ admin_info.first_name }} {{ admin_info.last_name }} </h2>
                    </div> {% endcomment %}
                    <div class="set-session-form">
                        <form method="post" action="">
                            {% csrf_token %}
                            <div class="grid-3">
                            <div>
                            <div class="section-heading"><p>General </p> </div>
                            <table>
                                {{ form1.as_table }}
                                <tr>
                                    <th>Id number</th>
                                    <td>
                                        <input type="text"  name="id_number" >
                                        
                                    </td>
                                </tr>
                                <tr>
                                    <th>contact phone</th>
                                    <td>
                                        <input type="text"  name="contact_phone"  >
                                    </td>
                                </tr>
                            </table></div>
                            <div>
                            <div class="section-heading"><p>For Students </p> </div>
                        <table>
                            
                              

                                <tr>
                                    <th>Group number</th>
                                    <td>
                                        <input type="text"  name="group_name"  >
                                        <span class="helptext"> only this syntax G1,2,3,4,... <br> is valid  </span>
                                    </td>
                                   
                                </tr>
                            </table></div>
                            <div>
                            
                            <div class="section-heading"><p>For Teatchers </p> </div>
                        
                        <table> 
                            <tr>
                                <th>Module</th>
                                <td>
                                    <input type="text"  name="Module"  >
                                </td>
                            </tr>
                        </table>
                        
                        
                        </div>
                        <div>
                            
                            <div class="section-heading"><p>For Technical Team or Administration
                                 </p> </div>
                        
                        <table> 
                            <tr>
                                <th>position</th>
                                <td>
                                    <input type="text"  name="position"  >
                                </td>
                            </tr>
                            
                        </table><div><div class="section-heading" style=" margin-top:20px"><p>For  Administration only
                            </p> </div>
                        
                            <select name="is_supervisor" id="id_role">
                                <option value="NO">No</option>
                              
                                <option value="YES">Yes</option>
                              
                                
                              
                              </select>
                        </div>
                        </div>
                    </div>
                            <button type="submit">Create</button>
                        </form>
                    </div>
                </div>
                <div class="chart" id="daughnut-chart">
                    <h2>Set Session</h2>
                    <div class="set-session-form">
                        <form method="post" action="">
                            {% csrf_token %}
                            <label>
                                <div>
                            <table>
                                {{ form.as_table }}
                            </table>
                            <div>
                            <button type="submit">Set Session</button>
                        </form>
                    </div>
                </div>
        </div>
    </div>

    <script>
        // Get all input elements
        const inputs = document.querySelectorAll('input');
    
        // Add event listeners to each input element
        inputs.forEach(input => {
            input.addEventListener('focus', function() {
                // Hide all helpartext elements
                document.querySelectorAll('.helptext').forEach(helpText => {
                    helpText.style.display = 'none';
                });
    
                // Find the adjacent helpartext element
                let adjacentHelpText = input.nextElementSibling;
                while (adjacentHelpText && !adjacentHelpText.classList.contains('helptext')) {
                    adjacentHelpText = adjacentHelpText.nextElementSibling;
                }
    
                // Display the adjacent helpartext element
                if (adjacentHelpText) {
                    adjacentHelpText.style.display = 'block';
                }
            });
    
            input.addEventListener('blur', function() {
                // Hide the adjacent helpartext element when the input is blurred
                let adjacentHelpText = input.nextElementSibling;
                while (adjacentHelpText && !adjacentHelpText.classList.contains('helptext')) {
                    adjacentHelpText = adjacentHelpText.nextElementSibling;
                }
    
                if (adjacentHelpText) {
                    adjacentHelpText.style.display = 'none';
                }
            });
        });
    
        
    </script>
</body>
</html>